-- phpMyAdmin SQL Dump
-- version 3.4.10.1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le : Jeu 24 Mai 2012 à 21:02
-- Version du serveur: 5.5.20
-- Version de PHP: 5.3.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `jeux`
--

-- --------------------------------------------------------

--
-- Structure de la table `games`
--

CREATE TABLE IF NOT EXISTS `games` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom` varchar(40) NOT NULL,
  `console` varchar(10) NOT NULL,
  `type` varchar(255) NOT NULL,
  `rate` int(11) NOT NULL,
  `img` text NOT NULL,
  `description` text NOT NULL,
  `age_requis` int(11) NOT NULL,
  `prix` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=41 ;

--
-- Contenu de la table `games`
--

INSERT INTO `games` (`id`, `nom`, `console`, `type`, `rate`, `img`, `description`, `age_requis`, `prix`) VALUES
(1, 'Disney Universe', 'wii', 'Action/Aventure', 11, 'image/wii/jaquette-disney-universe-wii-cover-avant-g-1319633784.jpg', 'Disney Universe est un jeu d''action/aventure sur Wii. Jouable à 4 en coopération, le soft vous permet d''évoluer dans les différents univers Disney tels que celui d''Alice au Pays des Merveilles ou de Monstres&Cie. Le titre propose au joueur plus de 40 costumes inspirés des célèbres personnages de la firme, chacun offrant des capacités spécifiques.', 7, 250),
(2, 'Rayman Origins  ', 'wii', 'Plates-formes', 19, 'image/wii/jaquette-rayman-origins-wii-cover-avant-g-1322067595.jpg', ' Rayman Origins est un jeu de plates-formes sur Wii. Le titre propose un gameplay à l''ancienne en deux dimensions et permet de revenir aux sources de la série. A travers près de 60 niveaux, le joueur doit libérer de petites créatures nommées Electoons et collecter des Lums en se méfiant des pièges et des nombreux ennemis qui l''attendent. Rayman Origins est également jouable à 4 en coopération.', 7, 240),
(3, 'Mario & Sonic aux Jeux Olympiques de Lon', 'wii', 'sport', 14, 'image/wii/jaquette-mario-sonic-aux-jeux-olympiques-de-londres-2012-wii-cover-avant-g-1320943550.jpg', 'Mario & Sonic aux Jeux Olympiques de Londres 2012 sur Wii est un party-game mettant en scène les personnages de Nintendo et Sega. Jouable jusqu''à 4, il propose toute une série d''épreuves sportives ainsi qu''un mode Dream composé de jeux bonus', 14, 340),
(4, 'Kirbys Adventure', 'wii', 'Plates-formes', 16, 'image/wii/jaquette-kirby-s-adventure-wii-wii-cover-avant-g-1321881985.jpg', ' Kirby''s Adventure sur Wii est un jeu qui nous fait vivre les nouvelles aventures du petit héros rose de la firme Nintendo, Kirby. Vous pourrez vous faire aider de trois compagnons pour chercher à reconstituer le vaisseau spatial de Magolor.', 16, 430),
(5, 'Captain Morgane et la Tortue d''Or', 'wii', 'Aventure /Point&Click', 11, 'image/wii/jaquette-captain-morgane-et-la-tortue-d-or-wii-cover-avant-g-1330093145.jpg', 'Disney Universe est un jeu d''action/aventure sur Wii. Jouable à 4 en coopération, le soft vous permet d''évoluer dans les différents univers Disney tels que celui d''Alice au Pays des Merveilles ou de Monstres&Cie. Le titre propose au joueur plus de 40 costumes inspirés des célèbres personnages de la firme, chacun offrant des capacités spécifiques.', 12, 230),
(6, 'Skylanders  Spyro''s Adventure  ', 'wii', 'Action/Plates-formes', 15, 'image/wii/jaquette-skylanders-spyro-s-adventure-wii-cover-avant-g-1318432913.jpg', ' Skylanders : Spyro''s Adventure est un jeu d''action-aventure sur Wii. On peut y incarner une trentaine de créatures en contrôlant des figurines qu''on doit positionner sur un socle fourni avec le jeu. Trois d''entre elles sont également incluses et les autres peuvent être achetées séparément. Par ailleurs, on trouve deux modes pour jouer en coopération avec un ami ou bien affronter un adversaire.', 7, 510),
(7, 'The Last Story', 'wii', 'Action / Jeu de Rôle', 17, 'image/wii/jaquette-the-last-story-wii-cover-avant-g-1329733280.jpg', 'The Last Story est un jeu d''action-RPG sur Wii. Zael et ses compagnons mercenaires devront faire face à de terribles menaces dans un titre à l''action constante. Le système de combat vous impose de protéger vos compagnons coûte que coûte en attirant les ennemis grâce au système de Magnétisme. Un mode multi permet de prendre part à des raids en coopération ou à des matches en versus.', 16, 390),
(8, 'conduit 2  ', 'wii', 'FPS', 15, 'image/wii/jaquette-conduit-2-wii-cover-avant-g-1303313078.jpg', ' The Conduit 2 est un jeu de tir à la première personne sur Wii. On contrôle l''Agent Ford prêt à en découdre face à une invasion alien. En plus de la campagne solo, un mode multi local ou en ligne paramétrable à souhait est aussi disponible.', 16, 290),
(9, 'Brothers in Arms Furious 4', 'PC', 'FPS', 16, 'image/pc/jaquette-brothers-in-arms-4-furious-pc-cover-avant-g-1307438179.jpg', 'Brothers in Arms Furious 4 est un jeu de tir à la première personne sur PC se déroulant durant la Seconde Guerre mondiale. Le titre revêt un aspect très arcade et permet à 4 joueurs, en sus du mode solo, d''incarner quatre furieux prêts à tout pour défaire des hordes de nazis toujours aussi belliqueux. De nombreuses armes et pièges sont disponibles et un système de customisation est présent.', 18, 60),
(10, 'Call of Juarez  The Cartel', 'PC', 'FPS', 10, 'image/pc/jaquette-call-of-juarez-the-cartel-pc-cover-avant-g-1315465411.jpg', 'Contrairement aux deux premiers épisodes sur PC, le jeu de tir à la première personne Call of Juarez : The Cartel se déroule à notre époque. Basé sur la coopération entre les trois héros principaux, le soft nous invite à affronter un cartel mexicain particulièrement violent. On devra exploiter au mieux les spécificités de chaque personnage pour faire le ménage à Los Angeles comme à Juarez.', 18, 150),
(11, 'Dead Rising 2  Off the Record', 'PC', 'Action / Beat''em all', 14, 'image/pc/jaquette-dead-rising-2-off-the-record-pc-cover-avant-g-1317395473.jpg', 'Off the Record est un jeu d''action sur PC. On y retrouve le héros du premier épisode, Frank West, dans une réinterprétation de l''attaque de zombies sur Fortune City. De nouveaux ennemis, véhicules et surtout une nouvelle histoire viennent changer la donne.', 18, 320),
(12, 'Diablo 3', 'PC', ' Jeu de Rôle / Action', 16, 'image/pc/jaquette-diablo-iii-pc-cover-avant-g.jpg', 'Diablo 3 sur PC est un hack''n slash (jeu de rôle orienté action) qui se déroule dans un univers dark fantasy 20 ans après les événements narrés dans Diablo 2. Le joueur a la possibilité de créer un héros parmi les cinq classes disponibles pour affronter le mal sous toutes ses formes. Bénéficiant d''un mode solo et multijoueur, Diablo III vous fera voyager aussi bien dans des niveaux déjà visités dans les précédents opus que dans de nouveaux territoires.', 18, 420),
(13, 'Prototype 2', 'PC', 'Action', 17, 'image/pc/jaquette-prototype-2-pc-cover-avant-g-1318497128.jpg', 'Prototype 2 est un jeu d''action sur PC. Le joueur y incarne James Heller, soldat en quête de vengeance après la disparition de sa famille, emportée par une épidémie meurtrière. Lui-même infecté, celui-ci dispose de pouvoirs dévastateurs qui lui permettent de se frayer un chemin dans les rues infestées de New York.', 18, 500),
(14, ' Resident Evil  Operation Raccoon City', 'PC', 'Action', 19, 'image/pc/jaquette-resident-evil-operation-raccoon-city-pc-cover-avant-g-1332320898.jpg', 'Resident Evil : Operation Raccoon City est un jeu d''action à la troisième personne sur PC. Dans cet opus résolument tourné vers le multijoueur, vous incarnez l''un des quatre membres de l''équipe de sécurité d''Umbrella et devez à tout prix éliminer toute preuve mettant en cause votre employeur ainsi que tous les survivants croisant votre route.', 18, 600),
(15, 'Shift 2 Unleashed', 'PC', 'Course / Simulation', 15, 'image/pc/jaquette-shift-2-unleashed-pc-cover-avant-g-1301326576.jpg', 'Shift 2 Unleashed est un jeu de simulation de courses sur PC. Le système Autolog est présent, ce qui vous permet d''être connecté aux autres joueurs et de voir leurs statistiques. La gestion des dégâts concerne aussi bien les voitures que les pistes, et vous pourrez prendre le volant pour déjouer tous les pièges auxquels vous ferez face.', 0, 200),
(16, 'Virtua Tennis 4', 'PC', 'Sport', 12, 'image/pc/jaquette-virtua-tennis-4-pc-cover-avant-g-1310714794.jpg', ' Virtua Tennis 4 sur PC est un jeu de tennis dans lequel le joueur a 4 saisons pour atteindre le sommet de la hiérarchie mondiale et remporter les 4 grands tournois. Les mini-jeux, chers à la série, sont au rendez-vous et permettent notamment d''affronter jusqu''à 3 autres joueurs.yer un chemin dans les rues infestées de New York.', 0, 210),
(17, 'Anarchy Reigns', 'xbox 360', 'Action', 18, 'image/xbox 360/jaquette-anarchy-reigns-xbox-360-cover-avant-g-1313781856.jpg', 'Anarchy Reigns est un jeu d''action sur Xbox 360. Ses créateurs le décrivent comme un jeu d''action/combat online. En effet, le soft inclut de nombreux modes multijoueurs tels que les modes Tag Team et Battle Royale ainsi que la possibilité de jouer en ligne. De nombreux combattants sont disponibles disposant de coups plus extravagants les uns que les autres.', 18, 600),
(18, 'Burnout Crash', 'xbox 360', 'Arcade / Action', 12, 'image/xbox 360/jaquette-burnout-crash-xbox-360-cover-avant-g-1312805482.jpg', 'Burnout Crash! est un jeu de courses téléchargeable sur le Xbox Live Arcade. Il s''agit plus d''un jeu de carambolages que d''un jeu de courses, le principe étant de débouler dans une intersection en causant le plus de dégâts possible sur les décors et les autres véhicules. Seize intersections et trois modes de jeu sont disponibles. Cette version Xbox 360 inclut une fonctionnalité Kinect.       ', 7, 300),
(19, 'Deus Ex  Human Revolution', 'xbox 360', 'FPS / Jeu de Rôle', 18, 'image/xbox 360/jaquette-deus-ex-human-revolution-xbox-360-cover-avant-g-1314277669.jpg', 'Deus Ex 3 sur Xbox 360 est un FPS/jeu de rôle, préquelle des précédents épisodes. Vous incarnez Adam Jensen, employé d''une entreprise spécialisée dans la biotechnologie. Suite à l''attaque de cette dernière par un mystérieux commando, votre enquête commence et vous amènera à parcourir l''univers cyberpunk typique de la série. Liberté d''action et choix à conséquences scénaristiques sont au rendez-vous de cet opus.     ', 18, 230),
(20, 'Dragon''s Dogma', 'xbox 360', 'Action', 14, 'image/xbox 360/jaquette-dragon-s-dogma-xbox-360-cover-avant-g-1326213803.jpg', 'Dragon''s Dogma est un jeu d''action sur Xbox 360. Dans un univers heroïc-fantasy, vous incarnez Glynn, un jeune homme à la recherche d''un puissant dragon qui lui a volé son coeur. Le héros est uni au dragon qu''il traque par un lien psychique et, tout au long de son périple, il devra terrasser d''imposantes créatures.', 16, 550),
(21, 'Mass Effect 3', 'xbox 360', 'Jeu de Rôle', 18, 'image/xbox 360/jaquette-mass-effect-3-xbox-360-cover-avant-g-1331287849.jpg', 'Mass Effect 3 est un jeu de rôle futuriste sur Xbox 360 où vous devez lutter contre les troupes de Cerberus, une organisation pro-humaine, et les emblématiques Moissonneurs. En parcourant la galaxie vous serez amené à effectuer des choix qui auront une incidence considérable sur la suite de votre aventure. Cet opus dispose d''un système de combat des plus dynamiques et offre au joueur la possibilité d''améliorer certaines parties de son arme.', 18, 510),
(22, 'Ninja Gaiden 3', 'xbox 360', 'Beat''em all', 12, 'image/xbox 360/jaquette-ninja-gaiden-3-xbox-360-cover-avant-g-1329817634.jpg', 'Ninja Gaiden 3 sur Xbox 360 est un jeu d''action ardu et sanglant plaçant le joueur dans la peau de Ryu Hayabusa, un ninja dont l''habileté n''a d''égale que sa maîtrise du katana. Cette fois-ci c''est à Londres que notre trancheur de membres préféré va jouer de l''épée du dragon face à de belliqueux terroristes.', 18, 600),
(23, 'Evolution Soccer 2012', 'xbox 360', 'Sport', 17, 'image/xbox 360/jaquette-pro-evolution-soccer-2012-xbox-360-cover-avant-g-1314192293.jpg', 'PES 2012 : Pro Evolution Soccer 2012 est une simulation de football sur Xbox 360. Le soft dispose d''une nouvelle intelligence artificielle et vous permet de contrôler n''importe quel joueur présent sur le terrain. Les licences officielles de la Ligue Europa et de la Ligue des Champions sont disponibles.', 0, 300),
(24, 'Resident evil 5', 'xbox 360', 'Action', 16, 'image/xbox 360/jaquette-resident-evil-5-xbox-360-cover-avant-g.jpg', 'Resident Evil 5 sur Xbox 360 est un jeu d''action/horreur dans lequel vous rejoignez Chris Redfield cette fois aux prises des victimes du virus T ayant frappé un village africain. Pendant le jeu, Chris rencontrera Sheva, une jeune femme qui l''aidera à venir à bout des nombreux ennemis. Mis en scène dans un environnement jusqu''alors inédit, le titre fait la part belle à l''action et à la coopération entre les deux protagonistes.', 18, 240),
(25, 'Assassin''s Creed : Revelations', 'ps3', 'Action / Aventure', 17, 'image/ps3/Assassin''s Creed  Revelations.jpg', 'Assassin''s Creed : Revelations est un jeu d''action-aventure sur playstationn 3. Doté de nouvelles armes et capacités, l''assassin Ezio est plus déterminé que jamais et tente de marcher sur les traces de son ancêtre Altair. L''intrigue nous transporte dans de nombreuses villes telles que Masyaf, Constantinople ou bien encore la Cappadoce. Le jeu permet également de s''étriper gaiement en multijoueur.', 18, 360),
(26, 'Battlefield 3', 'ps3', 'FPS', 15, 'image/ps3/jaquette-battlefield-3-playstation-3-ps3-cover-avant-g-1319471787.jpg', 'Battlefield 3 est un FPS sur playstationn 3. A travers une campagne solo et une série de 6 missions coopératives, le jeu vous plonge dans un conflit moderne qui embrase les 4 coins du monde. Battlefield 3 propose en outre un mode multijoueur complet capable d''accueillir 24 joueurs sur 9 maps qui s''adaptent au mode de jeu choisi. Avec ses 4 classes customisables, ses armes modifiables, ses nombreux véhicules et son système d''escouade, il s''oriente principalement vers le jeu d''équipe.', 16, 320),
(27, 'Call of Duty  Modern Warfare 3', 'ps3', 'FPS', 17, 'image/ps3/jaquette-call-of-duty-modern-warfare-3-playstation-3-ps3-cover-avant-g-1320657923.jpg', 'Call of Duty : Modern Warfare 3 est un FPS sur PS3 qui s''inscrit dans le contexte d''une hypothétique Troisième Guerre mondiale. Suite directe des deux précédents volets, la campagne nous entraîne aux 4 coins du monde pour affronter les Russes. De Manhattan en passant par Londres ou Paris, le jeu enchaîne les situations de combat et offre une mise en scène calquée sur celle des grands films de guerre hollywoodiens. Le jeu propose également un mode multijoueur complet ainsi qu''un mode coop.', 18, 530),
(28, 'Driver  San Francisco', 'ps3', 'course', 16, 'image/ps3/jaquette-driver-san-francisco-playstation-3-ps3-cover-avant-g-1307698028.jpg', 'Driver : San Francisco est un jeu de courses sur PS3 dans lequel vous incarnez Tanner, un homme tombé dans le coma suite à un accident. Parcourez les 320 kilomètres de routes au volant d''une centaine de véhicules, des grosses cylindrées à la Fiat 500. Grâce au système de shift, il vous sera possible de changer de voiture comme bon vous semble à l''aide d''un curseur.', 12, 250),
(29, ' FIFA 2012', 'ps3', 'Sport', 18, 'image/ps3/jaquette-fifa-12-playstation-3-ps3-cover-avant-g-1317225870.jpg', 'Fifa 12 est une simulation de football sur PS3 qui vous fait revivre l''intensité d''un match tout en étant confortablement installé chez vous. Les actions gagnent en réalisme grâce à un tout nouveau moteur de jeu, une jouabilité toujours plus poussée et un nouveau système de collision. Nouveauté de cette opus, le système Intelligence Pro rendant les joueurs plus réactifs que jamais.', 0, 400),
(30, 'Hitman Absolution', 'ps3', 'Infiltration', 17, 'image/ps3/jaquette-hitman-absolution-playstation-3-ps3-cover-avant-g-1331040396.jpg', 'Hitman : Absolution sur playstationn 3 est un jeu d''Infiltration dans lequel on retrouve un Agent 47 toujours aussi méticuleux et efficace. Ses contrats le mèneront aux quatre coins du globe et lui permettront cette fois de régler ses conflits intérieurs.', 18, 600),
(31, 'Jurassic Park  The Game', 'ps3', 'Aventure / Action', 16, 'image/ps3/jaquette-jurassic-park-the-game-playstation-3-ps3-cover-avant-g-1305911540.jpg', 'Jurassic Park : The Game est un jeu d''action/aventure en téléchargement sur PS3 se déroulant en parallèle du film Jurassic Park. Le jeu vous place dans la peau de nouveaux personnages devant survivre à l''enfer du célèbre parc. Un seul objectif, quitter l''île en un seul morceau.', 0, 430),
(32, 'Need for Speed  The Run', 'ps3', 'course', 14, 'image/ps3/jaquette-need-for-speed-the-run-playstation-3-ps3-cover-avant-g-1321548643.jpg', 'Need for Speed : The Run est un jeu de courses sur playstationn 3 où le joueur prend part à d''intenses courses-poursuites. Orienté arcade, le titre vous transporte dans des environnements variés tels qu''un étroit canyon ou une grande ville en effervescence. Le jeu utilise le moteur Frostbite 2, connu pour sa gestion des destructions de qualité.', 16, 290),
(33, 'Gran Turismo', 'psp', 'course', 13, 'image/psp/jaquette-gran-turismo-playstation-portable-psp-cover-avant-g.jpg', 'Gran Turismo sur PSP est un jeu de courses comportant 800 véhicules et 35 circuits. Le mode solo propose des courses simples, des courses contre-la-montre, des épreuves de drift et un mode d''aide au pilotage. Le jeu est jouable jusqu''à 4 en ad hoc et les joueurs ont la possibilité d''échanger les voitures entre eux.', 0, 800),
(34, 'Grand Theft Auto  Chinatown Wars', 'psp', 'Action', 18, 'image/psp/jaquette-grand-theft-auto-chinatown-wars-playstation-portable-psp-cover-avant-g.jpg', 'Grand Theft Auto : Chinatown Wars est une adaptation sur PSP de l''épisode déjà sorti sur DS. Le joueur traverse des environnements ouverts et interactifs et finit par découvrir la vérité cachée derrière les rumeurs de crimes et de corruptions au sein de la Triade.', 18, 120),
(35, 'Jak and Daxter : The Lost Frontier', 'psp', 'Action / Plates-formes', 11, 'image/psp/jaquette-jak-and-daxter-the-lost-frontier-playstation-portable-psp-cover-avant-g.jpg', 'Jak and Daxter : The Lost Frontier sur playstationn Portable reprend là où le troisième volet s''est arrêté. Vous retrouvez le duo parti aider Kieira à devenir une Sage pour sauver le monde. Le titre inclut des phases en véhicules dans des décors très aériens.', 12, 140),
(36, 'LittleBigPlanet ', 'psp', 'Plates-formes', 17, 'image/psp/jaquette-littlebigplanet-playstation-portable-psp-cover-avant-g.jpg', 'LittleBigPlanet sur PSP est un jeu de plates-formes. Vous dirigez un petit personnage (que vous aurez créé au préalable) dans un univers qu''il faut traverser en vous servant des objets récoltés et de ceux présents sur le tableau. Aidez-vous de l''environnement et de vos amis pour surmonter les obstacles et créez vos propres niveaux pour les proposer aux autres joueurs via Internet.', 7, 190),
(37, 'Metal Gear Solid  Peace Walker', 'psp', 'Infiltration', 17, 'image/psp/jaquette-metal-gear-solid-peace-walker-playstation-portable-psp-cover-avant-g.jpg', 'Metal Gear Solid : Peace Walker est un jeu d''infiltration sur playstationn Portable. Vous incarnez Naked Snake alias Big Boss dans une aventure qui se déroule 10 ans après l''histoire de Metal Gear Solid 3. L''accent est mis sur la coopération dans ce titre puisque vos compagnons joueront de véritables clones de Snake à vos côtés dans un scénario basé sur la crise des missiles de Cuba.', 18, 310),
(38, 'SoulCalibur : Broken Destiny', 'psp', 'combat', 16, 'image/psp/jaquette-soulcalibur-broken-destiny-playstation-portable-psp-cover-avant-g.jpg', 'SoulCalibur : Broken Destiny est un jeu de combat sur PSP. On retrouve les personnages des précédents volets comme Mitsurugi, Taki ou encore Tira mais aussi un combattant totalement inédit : Dampierre. Faisant honneur à la série des SoulCalibur, ce nouvel opus vous propose aussi de contrôler un personnage issu d''un autre jeu à savoir Kratos : le héros de la série God of War.', 16, 100),
(39, 'Undead Knights', 'psp', 'Action', 13, 'image/psp/jaquette-undead-knights-playstation-portable-psp-cover-avant-g.jpg', 'Undead Knights sur playstationn Portable est un jeu d''action qui vous propose d''incarner un chevalier mort-vivant à la tête d''un groupe de zombies. Partez, à l''aide de votre armée, assaillir de nombreuses forteresses et massacrez leurs occupants. Vous aurez la possibilité de ressusciter chacun de vos ennemis tombés au combat pour que ceux-ci viennent grossir les rangs de votre armée. Multipliez les combos dévastateurs sur un fond de musique métal pour assouvir vos sombres desseins.', 18, 200),
(40, 'Valkyria Chronicles 2', 'psp', 'Jeu de Rôle / Tactique', 18, 'image/psp/jaquette-valkyria-chronicles-ii-playstation-portable-psp-cover-avant-g.jpg', 'Valkyria Chronicles 2 est un jeu de rôle tactique sur PSP. L''histoire vous propulse dans la peau d''Avan Hardins, un jeune homme étudiant l''art de la guerre à l''académie militaire de Gallia. Il va prendre les armes pour défendre son peuple face à un nettoyage ethnique organisé par des factions révolutionnaires.', 16, 100);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
